- .gitignore
- Source/Public/Invoke-BicepBuild.ps1
Added an `-ExcludeFile` parameter to `Invoke-BicepBuild`. When using `Invoke-BicepBuild` to compile all .bicep files in a folder the parameter can be used to exclude a .bicep file that is still "work in progres". 
Example: 
`Invoke-BicepBuild -Path C:\Bicep\Modules\ -ExcludeFile subnet.bicep`
> Added -ExcludeFile parameter to Invoke-BicepBuild

- Source/Bicep.psd1
- Source/Private/GenerateParameterFile.ps1
Fixes issue #8 where `Invoke-BicepBuild -GenerateParameterFiles` cannot handle array and object parameters without default value properly.
Bump version number to 1.1.1
> Fixes issue #8

- Source/Private/GenerateParameterFile.ps1
- Source/Private/WriteBicepDiagnostic.ps1
- Source/Public/Build-Bicep.ps1
Parameter DestinationPath is added to GenerateParameterFile which can be used in the parameter set FromContent.
Changed the call from Build-Bicep to use this parameter.
Also fixed WriteBicepDiagnostic so that it doesnt give errors when using -WhatIf or -Confirm.
Closes #45
> Added DestinationPath parameter to GenerateParameterFile

- Docs/Help/Build-Bicep.md
- Source/Private/ParseBicep.ps1
- Source/Private/WriteBicepDiagnostic.ps1
- Source/Public/Build-Bicep.ps1
- Source/Public/ConvertTo-Bicep.ps1
- scripts/downloadAssemblies.ps1
Now outputs all diagnostic messages to the Information stream
If any errors are output we will write-error to support -ErrorAction Stop
Each diagnostic message will be tagged with Information, Warning or Error to be able to tell them apart programmatically.
> Alternative diagnostics

- Source/Public/Install-BicepCLI.ps1
If -force flag is used and we find a previously installed version of BicepCLI we now show a warning. 
It is still possible to run the installation, and no uninstallation will be performed, according to discussions.
> #59 Added warning to Install-BicepCLI if multiple versions are installed

- Source/Public/ConvertTo-Bicep.ps1
Using ConvertTo-Bicep to decompile an ARM template with nested module would result in invalid error messages since we tried to build each individual bicep file created.
Now only builds the "parent" bicep files and output should be identical to `bicep decompile`
> Now builds only parent bicep file when decompiling

- Source/Public/Get-BicepApiReference.ps1
Contains the following improvements:
* When Get-BicepApiReference is used without parameters, the correct url will now be opened (without the trailing slashes). Fixes #94
* Added suffix to url so it shows bicep tabs on template pages by default. Closes #92
I know we might want to fix one issue in each PR, but these two were so small so I lumped them together.
> Get-BicepApiReference improvements

- Source/Public/Install-BicepCLI.ps1
Added sleep between downloading the installer and starting the installation to avoid file lock errors.
Closes #95
> Install-BicepCLI no longer throws file locked error

- .github/workflows/RunTests.yaml
- scripts/downloadDependencies.ps1
Since we not only download assemblies, the file downloadAssemblies.ps1 has been renamed to downloadDependencies.ps1.
Changed stacknames as well for push/pop-location.
Closes #90
> Renamed downloadAssemblies.ps1 to downloadDependencies.ps1

- Source/Private/TestBicep.ps1
The executable is by default installed as `bicep` and not `Bicep`.
For cross-plattform compability and to be consistent with InstalledBicepVersion.ps1 the bicep command is changed from `Bicep` to `bicep` in TestBicep.ps1.
Closes #107
> fix: bicep command casing (fixes #107)

- Docs/Help/Convert-JsonToBicep.md
- Source/Bicep.psd1
- Source/Public/Convert-JsonToBicep.ps1
- Source/Public/ConvertTo-Bicep.ps1
- Source/en-US/Bicep-help.xml
A first draft to fix feature request #105.
To use the feature:
```
$json = @"
[
{
"properties": {
"NSGName": "subnet2-nsg",
"SubnetName": "subnet2",
"RouteName": "",
"disableBgpRoutePropagation": true,
"routes": []
}
},
{
"properties": {
"NSGName": "subnet3-nsg",
"SubnetName": "subnet3",
"RouteName": "",
"disableBgpRoutePropagation": false,
"routes": []
}
}
]
"@
Convert-JsonToBicep -String $jsonSnippet
```
Or:
`Convert-JsonToBicep -String '{"key": "value", "anotherKey": "anotherValue"}'`
> New command Convert-JsonToBicep

- Docs/Help/Convert-JsonToBicep.md
- Source/Public/Convert-JsonToBicep.ps1
This includes one functional fix, and two minor details.
1) Safe method for getting path to temp directory
Using `$env:TEMP` is a Windows-only way of getting the temp directory.
By replacing this with `[System.Io.Path]::GetTempPath()` it allows
the Convert-JsonToBicep function to work across all platforms.
2) Allow Convert-JsonToBicep to receive pipeline input
This allows the function to process pipeline input to be used
in common Powershell scripting patterns.
3) Trailing whitespace removals (editor formatting, yay)
> Convert-JsonToBicep: Use safe path for tmp/temp and allow pipeline input

- Docs/Help/Install-BicepCLI.md
- Docs/Help/Uninstall-BicepCLI.md
- Docs/Help/Update-BicepCLI.md
- Source/Public/Install-BicepCLI.ps1
- Source/Public/Uninstall-BicepCLI.ps1
- Source/Public/Update-BicepCLI.ps1
- Source/en-US/Bicep-help.xml
Adds error/info message and exits from
- Install-BicepCLI
- Update-BicepCLI
- Uninstall-BicepCLI
on non-Windows systems.
Closes #116
> fix: Error message on Windows-only commands for Mac/Linux

- Source/Private/ParseBicep.ps1
- Source/Public/Convert-JsonToBicep.ps1
- Source/Public/ConvertTo-Bicep.ps1
This PR fixes an issue with the latest bicep assemblies `v0.3.539`. New methods have been added to `[Bicep.Core.TypeSystem.Az.AzResourceTypeProvider]` and we need to specify which one to use instead of using `::new()`. 
Updated the following functions with `[Bicep.Core.TypeSystem.Az.AzResourceTypeProvider]::CreateWithAzTypes()` instead of `[Bicep.Core.TypeSystem.Az.AzResourceTypeProvider]::new()`
- `ParseBicep.ps1`
- `Convert-JsonToBicep.ps1`
- `ConvertTo-Bicep.ps1`
Closes #147
> Updated to CreateWithAzTypes() method for AzResourceTypeProvider

- .github/workflows/RunTests.yaml
- Docs/Help/Build-Bicep.md
- Docs/Help/Convert-BicepParamsToDecoratorStyle.md
- Source/Bicep.psd1
- Source/Private/ConvertToHashtable.ps1
- Source/Private/ParseBicep.ps1
- Source/Public/Build-Bicep.ps1
- Source/Public/Convert-BicepParamsToDecoratorStyle.ps1
- Source/en-US/Bicep-help.xml
Added new command `Convert-BicepParamsToDecoratorStyle` mentioned in #133 
- New command added `Convert-BicepParamsToDecoratorStyle`
- Added an `-IgnoreDiagnostics` switch to `ParseBicep` and `BuildBicep` to support the new command without outputting diagnostics
- Updated help file
- Fixed docs for `Build-Bicep` and created docs for `Convert-BicepParamsToDecoratorStyle`
How it works:
**params.bicep**
```bicep
param location string = resourceGroup().location
param sku string {
default: 'Premium'
allowed: [
'Standard'
'Premium'
]
}
param publicipcount int {
default: 1
metadata: {
description: 'Specifies the number of public IPs to allocate to the firewall when deploying Azure Firewall'
}
}
param psk string {
secure: true
}
```
Convert the parameters from input `.bicep` file to decorator …
> New command Convert-BicepParamsToDecoratorStyle

- Docs/Help/Build-Bicep.md
- Docs/Help/New-BicepParameterFile.md
- Source/Private/GenerateParameterFile.ps1
- Source/Public/Build-Bicep.ps1
- Source/Public/New-BicepParameterFile.ps1
- Source/en-US/Bicep-help.xml
This PR partially closes #25. But I'm not sure if we need the `-Default` option mentioned in the issue or not. 
- Replaced the `-GenerateParameterFile` switch with two new switches in ´Build-Bicep`
- `-GenerateAllParametersFile` generates a parameter file with all parameters in the bicep file
- `-GenerateRequiredParametersFile` generates a parameter file with the required parameters only
- Since we already have six parameter sets for `Build-Bicep` I've added a check if someone uses both switches at the same time and will then choose `All` and write a warning instead of adding another parameter set.
- Added the parameter `-Parameters` to `New-BicepParameterFile`, accepts inputs `All` or `Required
- `All` generates a parameter file with all parameters in the bicep file
- `Required` …
> Added options for generate parameter file

- Source/Private/ConvertToHashtable.ps1
Fixes #154 
Noticed that `Convert-JsonToBicep` returns empty arrays as `null` and single value arrays as `string`. Updated `ConvertToHashtable.ps1` to handle these cases.
To test:
```powershell
$json = @"
[
{
"properties": {
"NSGName": "subnet2-nsg",
"SubnetName": "subnet2",
"RouteName": "",
"disableBgpRoutePropagation": true,
"routes": []
}
},
{
"properties": {
"NSGName": "subnet3-nsg",
"SubnetName": "subnet3",
"RouteName": "",
"disableBgpRoutePropagation": false,
"routes": [
"steffe"
]
}
},
{
"properties": {
"NSGName": "subnet4-nsg",
"SubnetName": "subnet3",
"RouteName": "mjau",
"disableBgpRoutePropagation": false,
"routes": [
"steffe",
"Bosse"
]
}
},
{
"properties": {
"NSGName": "subnet4-nsg",
"SubnetName": "subnet3",
"RouteName": "mjau",
"disableBgpRoutePropagation": false,
"routes": …
```
> Fix ConvertToHashTable empty or single value arrays

- .github/workflows/RunTests.yaml
Removed required version from Pester, possible fix: https://github.com/pester/Pester/pull/1941
> Removed required version from Pester

- Source/Public/ConvertTo-Bicep.ps1
Changed AbsolutePath to LocalPath in order for ConvertTo-Bicep to be able to handle whitespace in the path.
> Use LocalPath instead of AbsolutePath

- Source/Public/New-BicepParameterFile.ps1
- Source/Public/Update-BicepParameterFile.ps1
Fixes #191. And closes #159.
Also added `-IgnoreDiagnostics` switch in New-BicepParameterFile. No need to output build warnings when working with parameter files.
> Update-BicepParameterFile fixes

- Source/Public/New-BicepParameterFile.ps1
- Source/Public/Update-BicepParameterFile.ps1
`New-BicepParameterFile` and `Update-BicepParameterFile` now validates that the bicep template can be built without errors. 
Closes #202
> New/Update-Parameter file now validates the Bicep template

- .github/workflows/RunTests.yaml
If the build step Publish test results fails for some reason, the whole job should not fail. Publishing the test results in a comment is just a nice feature, not required.
This change make this step continue even if it fails.
Closes #225
> Workflow step "Publish test results" now continues on error

- Docs/bicep-version-comparison.md
- README.md
- Source/Bicep.psd1
- scripts/downloadDependencies.ps1
Updated module version:
- Bumped version in manifest
- Bumped version in README shield
- Added new version to version comparison docs
- Updated downloadDependencies.ps1 to download BicepNet 1.0.6
> Updated module version to 2.1.0

- Docs/Help/Get-BicepConfig.md
- Source/Bicep.psd1
- Source/Public/Build-Bicep.ps1
- Source/Public/Get-BicepConfig.ps1
- Tests/Get-BicepConfig.Tests.ps1
Fixes #263
Added new command `Get-BicepConfig` that finds the `bicepconfig.json` file in use and the current configuration for bicep.
Example:
```powershell
#Get default config
$bicepConfig=Get-BicepConfig -Scope Default
$bicepConfig.Config
$bicepConfig=Get-BicepConfig -Scope Merged -Path c:\bicepTemplates\storage.bicep
$bicepConfig.Config
Get-BicepConfig -Path c:\bicepTemplates\storage.bicep
```
1. Adds new command `Get-BicepConfig`
2. Adds tests for `Get-BicepConfig`
3. Added command to manifest
> Added new command `Get-BicepConfig`

- Docs/Help/Get-BicepMetadata.md
- Source/Bicep.psd1
- Source/Public/Get-BicepMetadata.ps1
- Source/en-US/Bicep-help.xml
- Tests/Get-BicepMetadata.Tests.ps1
- Tests/supportFiles/bicepWithMeta.bicep
Fixes #277
Added new command to get Bicep metadata from templates
```powershell
Get-BicepMetadata -Path .\myTemplate.bicep
Get-BicepMetadata -Path .\myTemplate.bicep -OutputType Json
Get-BicepMetadata -Path .\myTemplate.bicep -OutputType Hashtable
Get-BicepMetadata -Path .\myTemplate.bicep -IncludeReservedMetadata
```
1. Added new commamd
2. Tests added
> Added new command `Get-BicepMetadata`

- Tests/Build-Bicep.Tests.ps1
- Tests/Clear-BicepModuleCache.Tests.ps1
- Tests/CompareBicepVersion.Tests.ps1
- Tests/Convert-JsonToBicep.Tests.ps1
- Tests/ConvertTo-Bicep.Tests.ps1
- Tests/ConvertToHashTable.Tests.ps1
- Tests/Find-BicepModule.Tests.ps1
- Tests/Get-BicepApiReference.Tests.ps1
- Tests/Get-BicepConfig.Tests.ps1
- Tests/Get-BicepMetadata.Tests.ps1
- Tests/Get-BicepVersion.Tests.ps1
- Tests/InstalledBicepVersion.Tests.ps1
- Tests/ListBicepVersions.Tests.ps1
- Tests/Module.tests.ps1
- Tests/New-BicepParameterFile.Tests.ps1
- Tests/Publish-Bicep.Tests.ps1
- Tests/Restore-Bicep.Tests.ps1
- Tests/TestBicep.Tests.ps1
- Tests/Update-BicepTypes.Tests.ps1
Fixes #289 
1. Add a Join-Path where there's a filepath resolution in tests - this should allow both Windows and Linux (in my case WSL) to work
2. A couple of tests had an invalid path to the module psd1
Tests pass on my WSL machine:
> Fix tests on WSL

- scripts/testBicepNet.ps1
Adds script to test new versions of BicepNet.PS
> Add script for testing BicepNet

- .github/workflows/build.yml
Fixes the release workflow which currently is broken because it depends on a specific version of a module which is downloaded as `latest` and has been updated since we built the workflow.
The module is now loaded regardless of version.
1. The broken release step at the end of the workflow.
> Fixes release workflow to load latest PowerShellForGitHub version

- GitVersion.yml
The configuration for `gitversion` pointed to master instead of main, which is why the recent release workflow failed. This PR changes the configuration to use the main branch instead.
> Configuration for `gitversion` for `main` instead of `master`

- .github/actions/build/action.yml
Updated variable for GitVersion in build action to ensure that the correct version is picked up.
This broke in #343 when configuration changed for GitVersion version 6.
> Updated semver variable for gitversion

- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
- PSBicep.Core/PSBicep.Core.csproj
- PSBicep/PSBicep.csproj
This PR adds support for debugging the module including the core module loaded in a separate AssemblyLoadContext, by embedding the symbols inside the DLL.
This will not affect the total size of the module, only move the .pdb files into the .dll files. The impact on performance is insignificant.
It also adds a task to VS Code to support debugging.
Image below shows a breakpoint hit inside the PSBicep.Core project, loaded in a separate ALC.
> Debugging support for ALC with VS Code tasks

- PSBicep.Core/BicepService.cs
- PSBicep.Core/Logging/DiagnosticLogger.cs
- PSBicep.Core/ServiceCollectionExtensions.cs
- PSBicep.Core/Services/BicepCoreService.cs
- PSBicep.Core/Services/BicepRegistryService.cs
- PSBicep/Commands/BaseCommand.cs
- PSBicep/LoadContext/BicepLoader.cs
Fixes #364
If you haven't already, read the full [contribution guide](https://github.com/PSBicep/PSBicep/blob/main/CONTRIBUTING.md). The guide may have changed since the last time you read it, so please double-check. Once you are done and ready to submit your PR, run through the relevant checklist below.
Fixes #364 
Replace this with a brief description of what this Pull Request fixes, changes, etc.
1. Removed ILogger and PSCmdlet from DependencyInjection in PSBicep.Core
2. Added methods for Initialize and Unload to DiagnosticLogger to be able to load/unload a PSCmdlet at runtime
3. Replace any ILogger reference with diagnosticLogger.Log() method.
4. Added a static BicepLoader class to the PSBicep project that lazy-loads the PSBicep Service if not loaded and acts as a singleton.
> Fix #364 by implementing a singleton of the BicepService
