README.md
Source/Bicep.psd1
Source/Private/GenerateParameterFile.ps1
Source/Public/Invoke-BicepBuild.ps1

Added -GenerateParameterFile to Invoke-BicepBuild.
1. Created new function GenerateParameterFile.ps1
2. Update Invoke-BicepBuild with functionality to generate ARM Template Parameter files
3. Bumped version number to 1.1.0 in module manifest
4. Updated README.md with new functionality

Added -GenerateParameterFile to Invoke-BicepBuild

---

Source/Public/Install-BicepCLI.ps1

#3 
Added progress bar to download of Install-BicepCLI.
The download now fetches latest path from Github API, and downloads file asynchronous.

Added statusbar to github download

---

Source/Private/TestBicep.ps1

Updated TestBicep function to fix issue #12.

Updated function to resolve issue #12

---

Source/Bicep.psd1
Source/Public/Uninstall-BicepCLI.ps1

This version does not force clean the $env:path variable.

Added basic functionality for Uninstall-BicepCLI

---

.github/workflows/RunTests.yaml
.gitignore
Source/Tests/Install-BicepBuild.Tests.ps1
Source/Tests/Module.tests.ps1

Added some initial pester tests and github action

Pester tests

---

Source/Tests/TestBicep.Tests.ps1

Added tests for TestBicep

---

Source/Public/Build-Bicep.ps1
Source/Public/ConvertTo-Bicep.ps1

Updated the comment based help for `Build-Bicep` and `ConvertTo-Bicep` with new parameters.

Updated comment based help with new parameters

---

Docs/Build-Bicep.md
Docs/ConvertTo-Bicep.md
Docs/Get-BicepVersion.md
Docs/Install-BicepCLI.md
Docs/Uninstall-BicepCLI.md
Docs/Update-BicepCLI.md
README.md

Added info to README.md:
- Now using assemblies instead of wrapping CLI
- Added info about maintainers
- Updated contributing section
- Removed cmdlet docs
Created new Docs folder and moved cmdlet documentation to separate files.

Updated readme.md with new info and moved cmdlet info to docs

---

Source/Tests/InstalledBicepVersion.Tests.ps1

Added tests for InstalledBicepVersion

Added tests for InstalledBicepVersion

---

Source/Private/GenerateParameterFile.ps1
Source/Public/Build-Bicep.ps1

Both Build-Bicep and GenerateParameterFile now have SupportsShouldProcess which means that -WhatIf and -Confirm is supported.
Closes #33

Added SupportsShouldProcess on Build-Bicep and GenerateParameterFile

---

Docs/Help/ConvertTo-Bicep.md
Source/en-US/Bicep-help.xml

-Updated the ConvertTo-Bicep.md with info about the AsString parameter
-Generated a new `Bicep-help.xml`

Updated help file

---

Source/Bicep.psd1

Updated manifest version to 1.3.0

Manifest version update to 1.3.0

---

Docs/Help/Update-BicepCLI.md
Source/Public/Update-BicepCLI.ps1

Added uninstaller to Update-BicepCLI.
Also added CmdLetBinding in order to get the -verbose flag.

#51 fixed Update-BicepCLI to run uninstaller before update

---

Docs/Help/Get-BicepApiReference.md
Source/en-US/Bicep-help.xml

1. Added help for `Get-BicepApiReference` by creating Get-BicepApiReference.md
2. Updated external help file

Help added for Get-BicepApiReference

---

Docs/Help/Build-Bicep.md

fixed typo in build-bicep help file

fixed typo in build-bicep help file

---

Docs/Help/Build-Bicep.md
Source/Public/Build-Bicep.ps1
Source/en-US/Bicep-help.xml

- Added `-AsHashtable` switch to `Build-Bicep`. Closes #81.
- Updated `Build-Bicep.md` help file.
- Update external help file.

Added -AsHashtable switch

---

Source/Bicep.psd1

Updated module manifest:
- New version number 1.4.1
- Added `Core` to `CompatiblePSEditions`
- Added IconUri
- Updated Description
Closes: #79, #80

Updated manifest with icon, description and compatible version

---

README.md

Updated shield version to 1.4.1 in Readme

Updated shield version to 1.4.1

---

Source/Bicep.psd1

Fixed the mistake with minimum PS version in manifest. 
And bumped version to 1.4.2 to allow update of the module in PS Gallery

Fixed minimum version in manifest

---

README.md

Forgot about that shield 😊. Time to automate the releases...

Update shield version to 1.4.2

---

scripts/mergedPRDetailsToReleaseDraft.ps1

Added the missing label to release notes body.
Closes #103

Added missing label to release body

---

README.md

Added Update-BicepTypes to readme

Added Update-BicepTypes to readme

---

scripts/downloadDependencies.ps1

Since importing version 13 of Newtonsoft.Json creates a conflict with version 12 that PowerShell itself has a dependency on, this little hack will revert the dependency of bicep to version 12.0.3 which should work with PowerShell 7.
This will buy us some time to look at alternative (and more robust) solutions.

Added hack to use old version of Newtonsoft.Json

---

Source/Private/TestModuleVersion.ps1
Source/Public/Build-Bicep.ps1

- Added new private function `TestModuleVersion.ps1` that checks if there is a newer version of the module available. Uses a module scoped variable to make sure that the test only run once in a session.
- Added the check to `Build-Bicep`
Should we add it to more commands?
Closes #119

Added check if new module version is available

---

README.md
Source/Bicep.psd1

Updated module manifest to 1.4.5

update module version to 1.4.5

---

CONTRIBUTING.md

fixed another broken link

---

Docs/Help/Build-Bicep.md
Source/en-US/Bicep-help.xml

removed "-" from documentation

removed "-" from documentation

---

README.md

Added @emilguden as maintainer to repo readme

Added new maintainer to readme

---

.github/workflows/RunTests.yaml

Added -RequiredVersion 5.1.1 when importing Pester

Added -RequiredVersion 5.1.1 when importing Pester

---

Docs/Help/Build-Bicep.md
Docs/Help/Convert-JsonToBicep.md
Source/Public/Build-Bicep.ps1
Source/en-US/Bicep-help.xml

Added the parameter -OutputPath.
Build-Bicep -Path .\vnet.bicep -OutputPath .\virtualNetork.json

Added parameter -OutputPath

---

Docs/Help/New-BicepParameterFile.md
Source/Bicep.psd1
Source/Public/New-BicepParameterFile.ps1
Source/en-US/Bicep-help.xml

Creates an ARM Template parameter file based on a bicep file. The parameter file can be used during deployment with Azure CLI or Azure PowerShell.
Most of the code was taken from #83 but cherry picking from that branch turned out to be a lot of work. Sorry @PalmEmanuel :)
Closes #139

Added New-BicepParameterFile

---

Source/Private/GenerateParameterFile.ps1

Added a default value for int params

---

README.md
Source/Bicep.psd1

- Updated module version to 1.4.6 in manifest
- Updated shield version to 1.4.6 in readme
- Updated some text in readme

Updated module to version 1.4.6

---

Source/Public/Build-Bicep.ps1
Source/Public/Convert-JsonToBicep.ps1
Source/Public/ConvertTo-Bicep.ps1
Source/Public/Get-BicepApiReference.ps1
Source/Public/Get-BicepVersion.ps1
Source/Public/Install-BicepCLI.ps1
Source/Public/New-BicepParameterFile.ps1
Source/Public/Uninstall-BicepCLI.ps1
Source/Public/Update-BicepCLI.ps1
Source/Public/Update-BicepTypes.ps1

Added the `TestModuleVersion` function to all public functions to notify users if there is a new version of the module available for download. 
Closes #145

Added new version available function to all public functions

---

README.md

changed version in shield again

changed version in shield

---

Source/Public/Convert-JsonToBicep.ps1

Fixed a bug in `Convert-JsonToBicep` that appeared after updating `ConvertToHashtable.ps1` to work for `Convert-BicepParamsToDecoratorStyle`

Fixed bug in Convert-JsonToBicep after update ConvertToHashtable.ps1 change

---

README.md

Updated version number to 1.4.7 in readme shield. Manifest already updated.

Updated version number to 1.4.7

---

README.md
Source/Bicep.psd1

Updated version to 1.5.0
- Module manifest
- README.md shield

Updated version to 1.5.0

---

Tests/Get-BicepApiReference.Tests.ps1

Co-authored-by: Emanuel Palm <PalmEmanuel@users.noreply.github.com>
Co-authored-by: Emil Gullbrandsson <emilguden@users.noreply.github.com>
Co-authored-by: nilsson-jens <nilsson-jens@users.noreply.github.com>
Co-authored-by: Simon Wåhlin <simon.wahlin@advania.com>
Co-authored-by: Björn Sundling <bjompen@users.noreply.github.com>

Added tests for Get-BicepApiReference

---

.github/workflows/RunTests.yaml
Tests/TestRunner.ps1

Updated the action to publish the test results. The results will be added as a comment to the PR.
While I was doing this change I also added a test runner script.

Publish test result

---

Docs/Help/Update-BicepParameterFile.md
Source/Bicep.psd1
Source/Public/Update-BicepParameterFile.ps1
Source/en-US/Bicep-help.xml

Created possible solution for updating Parameter files according to issue #159.
Added cmdlet Update-BicepParameterFile and updated Docks / Help Files.

Update bicep parameter file #159

---

Docs/Help/Test-BicepFile.md
Source/Bicep.psd1
Source/Private/ParseBicep.ps1
Source/Private/WriteBicepDiagnostic.ps1
Source/Public/Test-BicepFile.ps1
Source/en-US/Bicep-help.xml

Adds functionality for testing the validity of a bicep file.
Closes #171

Added function Test-BicepFile

---

Source/Private/ListBicepVersions.ps1
Source/Private/ParseBicep.ps1
Source/Public/Get-BicepApiReference.ps1

Removed whitespace in two files and fixed a misspelling in ParseBicep.

Typo fix in ParseBicep message

---

README.md
Source/Bicep.psd1

Do not merge, but please approve.
Verision 1.5.1 bump:
- Updated version i module manifest
- Updated shield in README.md
- Added new commands to README.md
- Update-BicepParameterFile
- Test-BicepFile

[DO NOT MERGE] Version 1.5.1 bump

---

Source/Public/Update-BicepParameterFile.ps1

Add Parameters parameter to Update-BicepParameterFile

---

Source/Bicep.psm1
Tests/Build-Bicep.Tests.ps1
Tests/CompareBicepVersion.Tests.ps1
Tests/Get-BicepApiReference.Tests.ps1
Tests/Get-BicepVersion.Tests.ps1
Tests/Install-BicepBuild.Tests.ps1
Tests/InstalledBicepVersion.Tests.ps1
Tests/ListBicepVersions.Tests.ps1
Tests/Module.tests.ps1
Tests/TestBicep.Tests.ps1
Tests/TestRunner.ps1

Made some general improvements to how the module loads and how tests are run.
Import changes:
* Changed how the module imports scripts. Now it dot sources scripts instead of executing them. This makes it more Pester friendly and makes code coverage work.
Changes in all tests:
* The module is now imported in BeforeAll instead of in the beginning of each script
* InModuleScope is only used when its really needed. This improves performance for code coverage.
Changes to TestRunner:
* Generates code coverage report
Removed file
* Removed Install-BicepBuild.Tests.ps1 which didnt test anything. (It was added in the past when we were setting up the test runner to have something to run)

General improvements for tests

---

Tests/Get-BicepApiReference.Tests.ps1

Now we have full coverage for Get-BicepApiReference.

Additional tests for Get-BicepApiReference

---

Source/Public/ConvertTo-Bicep.ps1

Added try/catch to hide error msg.
I bet it can be done much nicer, any feedback is appreciated!

Added try/catch to hide error msg

---

Source/Public/ConvertTo-Bicep.ps1

Updated no files found message in ConvertTo-Bicep

---

README.md
Source/Bicep.psd1

- Updated manifest:
- Added pre-release tag
- Added info about possibility to test bicep files to description
- Changed minimum version from `7.0` to `7.1`
- Updated README with install instructions for pre-release versions

Prepped for pre-release version

---

Source/Public/Build-Bicep.ps1

Updated `Build-Bicep` to also include the pre-release version in ARM template metadata.

Added support for pre-release to template metadata

---

Docs/bicep-version-comparison.md

Added a table that shows which assembly version is used for each module version.

Added version comparison to docs

---

CONTRIBUTING.md

Updated contributing guide to reflect what's new with BicepNet

Updated contributing guide with info about BicepNet

---

scripts/downloadDependencies.ps1

Updated `donwloadDependencies.ps1` to use BicepNet version 1.0.4

Updated to BicepNet 1.0.4

---

Source/Bicep.psd1

Updated pre-release tag in module manifest to `Preview2`

Updated pre-release tag in module manifest

---

Docs/Help/ConvertTo-Bicep.md
Source/en-US/Bicep-help.xml

- Updated external help file to include changes to `ConvertTo-Bicep` and the implementation of the `-Force` flag. 
- Some minor typos and formatting in `ConvertTo-Bicep.md`

Updated external help file

---

CONTRIBUTING.md
Docs/Help/Build-Bicep.md
Docs/Help/ConvertTo-Bicep.md
Docs/Help/Get-BicepVersion.md
Docs/Help/Install-BicepCLI.md
Docs/Help/Update-BicepCLI.md
Source/Private/TestModuleVersion.ps1
Source/en-US/Bicep-help.xml
scripts/mergedPRDetailsToReleaseDraft.ps1

Updated all links from `StefanIvemo/BicepPowerShell` to `PSBicep/PSBicep`.

Updated all links to PSBicep/PSBicep

---

Docs/bicep-version-comparison.md

Updated version comparison table with new versions and added BicepNet to the table.

Updated version comparison table

---

Source/Public/Update-BicepTypes.ps1
Tests/Get-BicepApiReference.Tests.ps1
Tests/Update-BicepTypes.Tests.ps1
scripts/downloadDependencies.ps1

Update-BicepTypes and downloadDependencies.ps1 now works again.
Closes #228

Update-BicepTypes is not removing types anymore

---

Source/Private/ConvertToHashtable.ps1
Source/Public/Convert-JsonToBicep.ps1
Source/Public/Install-BicepCLI.ps1
Source/Public/New-BicepParameterFile.ps1
Source/Public/Uninstall-BicepCLI.ps1
Source/Public/Update-BicepCLI.ps1
Source/Public/Update-BicepParameterFile.ps1
scripts/mergedPRDetailsToReleaseDraft.ps1

Replaced "!" with "-not" for consistency.
Closes #220

Replaced "!" with "-not"

---

Docs/Help/Build-Bicep.md
Docs/Help/Publish-Bicep.md
Docs/Help/Restore-Bicep.md
Docs/bicep-version-comparison.md
Source/Bicep.psd1
Source/Public/Build-Bicep.ps1
Source/Public/Publish-Bicep.ps1
Source/Public/Restore-Bicep.ps1
Source/en-US/Bicep-help.xml
Tests/Publish-Bicep.Tests.ps1
Tests/Restore-Bicep.Tests.ps1
Tests/supportFiles/workingBicep.bicep
scripts/downloadDependencies.ps1

Closes #221
Implement changes from [BicepNet #5](https://github.com/PSBicep/BicepNet/pull/5).

Implement v.0.4.1008 support

---

.github/workflows/RunTests.yaml
Source/Private/ConvertToHashtable.ps1
Tests/ConvertToHashTable.Tests.ps1
Tests/ListBicepVersions.Tests.ps1
Tests/TestRunner.ps1

Testrunner has been improved to be easier to use when writing tests.
Added tests to ListBicepVersion
Added tests to ConvertToHashTable
Minor bugfix: ConvertToHashTable can now handle hashtables and properties that are hashtables (including ordered).

Added tests and improved testrunner

---

Source/Private/GenerateParameterFile.ps1

GenerateParameterFile no longer creates empty parameter files

---

Docs/Help/Find-BicepModule.md
Source/Bicep.psd1
Source/Public/Find-BicepModule.ps1
Tests/Find-BicepModule.Tests.ps1

Closes #241
- Implemented command `Find-BicepModule`
- Added markdown help file
- Added really basic tests 😊

Implemented Find-BicepModule

---

Source/Public/Convert-JsonToBicep.ps1

Fixes #256 
1. Replace Write-Host with Write-Output. Since Write-Host does not write to the output stream, nothing is returned from the function.

Convert-JsonToBicep bugfix

---

README.md
Source/Bicep.psd1
Source/en-US/Bicep-help.xml
scripts/downloadDependencies.ps1

Please approve without merging:
- Updated BicepNet version in downloaddependencies.ps1
- Updated external help file
- Added new commands to readme.md
- Updated module manifest version

Prepped module for version 2.2.0

---

Tests/Convert-JsonToBicep.Tests.ps1
Tests/supportFiles/nsgRule.json

Added tests to `Convert-JsonToBicep`
Improvement

Added tests to `Convert-JsonToBicep`

---

Source/Public/New-BicepParameterFile.ps1
Tests/New-BicepParameterFile.Tests.ps1

If you haven't already, read the full [contribution guide](https://github.com/PSBicep/PSBicep/blob/main/CONTRIBUTING.md). The guide may have changed since the last time you read it, so please double-check. Once you are done and ready to submit your PR, run through the relevant checklist below.
Fixes #267 
- Fixed bug caused by changes in BicepNet
- Added tests for `New-BicepParameterFile`
1. Fixed bug

Fixes issue generating parameter files

---

Docs/Help/Get-BicepConfig.md
Source/en-US/Bicep-help.xml

1. Updated help file to reflect the latest changes to the command

Updated help for `Get-BicepConfig`

---

Tests/Get-BicepConfig.Tests.ps1

Update tests for Get-BicepConfig to wait for file handle to be released.

Add wait for file handle to be released

---

Docs/bicep-version-comparison.md
README.md
Source/Bicep.psd1

Prep for version 2.3.2
- Updated `bicep-version-comparison.md` with new versions
- Updated PS Gallery shield in readme
- Updated manifest version

Updated for version 2.3.2

---

Docs/Help/Build-Bicep.md
Source/Public/Build-Bicep.ps1

Fixes #285 
Added new switch `-Compress` to `Build-Bicep` to reduce the file size of the outputted ARM json.

Added -Compress to Build-Bicep

---

Docs/Help/Build-Bicep.md
Docs/Help/Clear-BicepModuleCache.md
Docs/Help/Convert-JsonToBicep.md
Docs/Help/ConvertTo-Bicep.md
Docs/Help/Export-BicepChildResource.md
Docs/Help/Export-BicepResource.md
Docs/Help/Get-BicepApiReference.md
Docs/Help/Get-BicepConfig.md
Docs/Help/Get-BicepMetadata.md
Docs/Help/Get-BicepVersion.md
Docs/Help/Install-BicepCLI.md
Docs/Help/New-BicepParameterFile.md
Docs/Help/Test-BicepFile.md
Docs/Help/Uninstall-BicepCLI.md
Docs/Help/Update-BicepCLI.md
Docs/Help/Update-BicepParameterFile.md
Docs/Help/Update-BicepTypes.md
Source/Bicep.psd1
Source/Public/Export-BicepChildResource.ps1
Source/Public/Export-BicepResource.ps1

Fixes #302 .
1. Implements `Export-BicepResource`
2. Implements `Export-BicepChildResource`

Export commands `Export-BicepResource` and `Export-BicepChildResource`

---

Source/Public/Clear-BicepModuleCache.ps1

Fixes #307 
Added `-Force` to `Remove-Item`

Fixes issue 307

---

Docs/Help/Build-Bicep.md
Docs/Help/Build-BicepParam.md
Source/Bicep.psd1
Source/Public/Build-BicepParam.ps1

Add Build-BicepParam support
1. Add Build-BicepParam support

Add Build-BicepParam support

---

Docs/Help/Format-BicepFile.md
Source/Bicep.psd1
Source/Public/Format-BicepFile.ps1

Implements a new command `Format-BicepFile` to match the CLI command bicep format.
Fixes #309.

New command `Format-BicepFile`

---

Docs/bicep-version-comparison.md
README.md

- Added new cool badge with link to preview version - added for visibility that there is a pre-release out
- Added preview commands to readme
- Updated version comparison article

2 4 0 preview

---

README.md

Replace this with a brief description of what this Pull Request fixes, changes, etc.
1. Updates README.md with the `Format-BicepFile` preview command.

Added `Format-BicepFile` preview command to readme

---

.build/tasks/PSBicep.CopyBicepNetPS.ps1
.build/tasks/PSBicep.GetBicepTypes.ps1
.github/workflows/build.yml
.gitignore
Source/Bicep.psd1
build.yaml

Fix build action

---

CHANGELOG.md
build.yaml

Fix publish action

---

Docs/Help/Get-BicepApiReference.md
Docs/Help/New-BicepMarkdownDocumentation.md
Source/Bicep.psd1
Source/Public/Get-BicepApiReference.ps1
Source/Public/New-BicepMarkdownDocumentation.ps1
Source/en-US/Bicep-help.xml

Draft: initial version for testing.

Draft: New bicep markdown documentation

---

GitVersion.yml

Change gitversion mode
Hopefully this will properly increase the preview version on each commit to main.

Change gitversion mode

---

Source/Private/GetGitHubReleaseVersion.ps1
Source/Private/ListBicepVersions.ps1
Source/Private/TestModuleVersion.ps1
Source/Public/Build-Bicep.ps1
Source/Public/Build-BicepParam.ps1
Source/Public/Clear-BicepModuleCache.ps1
Source/Public/Convert-JsonToBicep.ps1
Source/Public/ConvertTo-Bicep.ps1
Source/Public/Export-BicepChildResource.ps1
Source/Public/Export-BicepResource.ps1
Source/Public/Find-BicepModule.ps1
Source/Public/Format-BicepFile.ps1
Source/Public/Get-BicepApiReference.ps1
Source/Public/Get-BicepMetadata.ps1
Source/Public/Get-BicepVersion.ps1
Source/Public/Install-BicepCLI.ps1
Source/Public/New-BicepParameterFile.ps1
Source/Public/Publish-Bicep.ps1
Source/Public/Restore-Bicep.ps1
Source/Public/Test-BicepFile.ps1
Source/Public/Uninstall-BicepCLI.ps1
Source/Public/Update-BicepCLI.ps1
Source/Public/Update-BicepTypes.ps1
Source/suffix.ps1
Tests/Get-BicepApiReference.Tests.ps1
Tests/Get-BicepVersion.Tests.ps1
Tests/ListBicepVersions.Tests.ps1
Tests/Update-BicepTypes.Tests.ps1

Fixes #341 
1. Consolidated calls to github releases API for getting release versions
2. Removed check for new module versions in each command
3. Added check for new module versions in suffix (only on module load)
4. Removed checks for bicep CLI version from Build-Bicep since we no longer depend on the CLI tool

Fix GitHub rate limit errors

---

.github/actions/build/action.yml
GitVersion.yml
scripts/mergedPRDetailsToReleaseDraft.ps1

Content-Type is now set for release script.

Content-type json for release script

---

scripts/mergedPRDetailsToReleaseDraft.ps1

Fixes broken release notes workflow
Replace this with a brief description of what this Pull Request fixes, changes, etc.
1. Fix broken release notes workflow

Add content-type to release notes workflow

---

Source/Public/Export-BicepResource.ps1

Add targetScope to Export-BicepResource

---

README.md

- Fixed a spelling misstake
- Updated list of active maintainers
- Updated shield verison

Fixed typo and info in readme

---

Docs/Help/Connect-Bicep.md
Source/Bicep.psd1
Source/Private/AssertAzureConnection.ps1
Source/Private/ValidateAzureToken.ps1
Source/Public/Connect-Bicep.ps1
Source/Public/Disconnect-Bicep.ps1
Tests/AssertAzureConnection.Tests.ps1

This pull request introduces significant updates to the `Connect-Bicep` functionality, including new features, parameter enhancements, and improved token validation logic. It also adds a new `Disconnect-Bicep` cmdlet and enhances the testing framework for better coverage. Below is a categorized summary of the most important changes:

Enhance Connect-Bicep
